### ISSUE TITLE
Feature Request: make the implementation cross platform

### ISSUE THREAD

**Issue by grahamehorner** [techyian/MMALSharp#100]
IMHO it would be great if this library also worked on the Windows 10 IoT Core platform; at present AFAIA there are no drivers available for Windows 10 IoT Core the Raspberry PI camera and support for the camera has been request from the community on a number of forums.  I'm not sure if this is possible or weather it would be a simple task or if a native library already exists that this wrapper could use when running under a Windows 10 IoT core environment

**Comment by techyian** [comment]
Hello,

Unfortunately this is not possible due to limitations in Windows 10 IoT - there is no hardware support to the camera module and therefore I'm unable to support it in this library. The feature request is best targeted at the Windows IoT developers.
