### ISSUE TITLE
Side Contact Question

### ISSUE THREAD

**Issue by d8ahazard** [techyian/MMALSharp#151]
Hi Ian,

Sorry for using the issue feature for this, but I couldn't find any other way to contact you.

I would like to write a c# wrapper for a c++ lib that does screen capture, and was hoping maybe I could pick your brain a bit for how to begin.

Is there an email address I could reach you at to discuss further - if you're up to it? Just looking for some pointers and tips.

Otherwise, I can be reached at donate.to.digitalhigh@gmail.com

**Comment by techyian** [comment]
Contacted via email.
