### ISSUE TITLE
Include XML Documentation in NuGet Package

### ISSUE THREAD

**Issue by daniel-lerch** [techyian/MMALSharp#35]
Visual Studio allows to make Documentation in Code:
```cs
/// <summary>
/// This class provides an interface to the Raspberry Pi camera module. 
/// </summary>
public sealed class MMALCamera 
{
}
```
But this documentation is not shown as long as you don't generate an XML file at build and include this file in your NuGet package. In Visual Studio you can go to `Project Settings->Build` and enable `XML documentation file`. This will generate a `MMALSharp.xml` in your output directory which you can include to your NuGet package. After this all developers that are using your library will see your documentation in Visual Studio.

**Comment by techyian** [comment]
Hi Daniel,

Thanks for bringing this to my attention :) I'll get it fixed ASAP.

Ian

**Comment by daniel-lerch** [comment]
Hi Ian,

I have fixed this issue locally as I made an own build.
Do you would like me to make a pull request?

Daniel

**Comment by techyian** [comment]
Sure, I'll check it over and merge in.

Thanks again,
Ian.
