### ISSUE TITLE
StyleCop Analysers and code style documentation

### ISSUE THREAD

**Issue by daniel-lerch** [techyian/MMALSharp#38]
The NuGet reference to StyleCop.Analysers was removed with e2d1b1bedd2499ab5b41f5dcfc0c303cea11a580 but the settings file is still existent. Maybe I have to install a plugin first.

A documentation would be very useful for contributors. And if active code analyzers are not an option, there should be a detailed article about the intended code style.

**Comment by techyian** [comment]
Hi Daniel,

I've removed the redundant stylecop json file, must have missed that when removing the StyleCop NuGet package. I wasn't awfully familiar with the StyleCop stuff and I didn't like how it forced code suggestions onto users of the NuGet package (there may be some way of disabling this?). I have ReSharper, so generally take advice from that now on how to best style the code.

**Comment by daniel-lerch** [comment]
Hi Ian,

ReSharper is a very good option too. Maybe I can get a student license of it.
I will try to configure StyleCop only to warn in some situation where I think it is useful.

Do you want documentation texts to end with a `.` or not?

**Comment by daniel-lerch** [comment]
Hi Ian,

> Do you want documentation texts to end with a `.` or not?

Microsoft's documentation texts always end with a full stop. I think it would be useful to make a decision to have consistent documentation. I would recommend to follow Microsoft's style but it is up to you to decide. If you only want full sentences to end with full stop or any other rule I haven't understood yet, please add this to a guideline anywhere in the repository.

Daniel

**Comment by techyian** [comment]
Hi Daniel,

Yes please - full stops at the end. I can see there are parts of the documentation that don't have them so I'll work through that when I get chance.

Ian

**Comment by daniel-lerch** [comment]
Hi Ian,
I will help if I find documentation without `.` at the end next time.

### Next question ###
Do you want the code and the documentation to be written in British or in American English?

**Comment by techyian** [comment]
British please for consistency with what's already there.

Thank you.

**Comment by techyian** [comment]
Added StyleCop Analyser Nuget package. Closing.
