### ISSUE TITLE
Fliename error with FrameToVideo utility (v0.4.2)

### ISSUE THREAD

**Issue by rrskybox** [techyian/MMALSharp#57]
When running the simple FrameToVideo sample code, my application is throwing an exception during the FrameToVideo method where it appears that the delimiter for the jpg extension is getting dropped (see below).
 

![image](https://user-images.githubusercontent.com/40242027/42190142-5da5a516-7e10-11e8-8b73-2e8c517af898.png)

The “.” between the filename and extension appears to be being dropped.  I looked at the VideoUtilities code and on line 48, any trailing “.”s appear to be trimmed correctly, but never reinserted before the extension is appended.

My test code follows.  I’ve modified it slightly from the original sample, but only superficially.

![image](https://user-images.githubusercontent.com/40242027/42190330-5a74150c-7e11-11e8-9167-1e0c8e88d4d3.png)

 
- Rick

**Comment by techyian** [comment]
Thanks for picking this up. In the process of installing ffmpeg so I can look at this for you.

**Comment by techyian** [comment]
The fix for this looks to be working correctly. You can pick it up from source or via MyGet pre-release until I next push to NuGet (finishing a few bits off around the preview renderer before doing so). Let me know if you run into any problems with the fix.

**Comment by rrskybox** [comment]
Much obliged.  Your project is a great concept with a superb implementation.  I'm looking forward to putting it to work.  I'll wait until it's up on NuGet to continue my experiments.  - Rick

**Comment by techyian** [comment]
Thanks Rick, I hope it can be useful to you.

Ian
