### ISSUE TITLE
Extract HDR raw images/video

### ISSUE THREAD

**Issue by DrDecipher** [techyian/MMALSharp#74]
This repo seems to be the most complete solution that I have found so far but I do not see this particular capability.

I’m looking to get the raw High exposure and Low exposure frames from the HDR mode for post processing not on the chip. 

Any thoughts or redirection would be appreciated.

**Comment by techyian** [comment]
Hi, there isn't anything built in to the library specifically for HDR capture, but a quick Google will provide some insight into how you can replicate HDR using the Pi sensor. Does [this](https://www.raspberrypi.org/forums/viewtopic.php?t=215343) give you any pointers? Exposure compensation can be tweaked in the config, check out the wiki for guidance.
