### ISSUE TITLE
Is there any way to open the camera indefinitely?

### ISSUE THREAD

**Issue by jjsoares90** [techyian/MMALSharp#76]
Hello,

All the examples involving video terminate the video after a set amount of time. Is there a way to leave the camera open (e.g. for RTMP streaming) indefinitely?

Thanks,

Jesse

**Comment by techyian** [comment]
Hi Jesse,

If you don't pass in a cancellation token to the ProcessAsync method it should leave the video running indefinitely. Let me know if that solves your issue.

Thanks,
Ian
